# Generated by Django 4.0.3 on 2022-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('new_confirmed', models.IntegerField()),
                ('total_confirmed', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('new_recovered', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('date', models.IntegerField()),
            ],
        ),
    ]
