# Generated by Django 4.0.3 on 2022-03-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='country',
            new_name='name',
        ),
    ]
